# Generated by Django 5.2.9 on 2026-01-02 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zeph",
            options={},
        ),
        migrations.AddField(
            model_name="zeph",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="zephs/"),
        ),
        migrations.AddField(
            model_name="zeph",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="posts.zeph",
            ),
        ),
        migrations.AlterField(
            model_name="zeph",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="zeph",
            name="content",
            field=models.TextField(),
        ),
    ]
