# Generated by Django 5.2.9 on 2026-01-05 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username can only contain letters, numbers, and underscores",
                        regex="^[a-zA-Z0-9_]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        3, message="Username must be at least 3 characters long"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=160),
        ),
    ]
